### PR TITLE
Depend on guzzle ~7.0

### PR DESCRIPTION
**Pull request by fritteli**
Any chance we could UP the dependency on guzzle to ~7.0? With this change, the app `files_external_dropbox` could be made compatible with Nextcloud 21.

See DJaeger/files_external_dropbox/issues/32

### CODE REVIEW

**Comment by fritteli** [comment]
@kunalvarma05 If there's anything wrong with this PR, please let me know, so that I can fix it.

**Comment by slightlydiff** [comment]
Thanks for you email.

Sorry but I am not available until Monday 26th July.  

For any hosting support issues please submit a ticket via https://my.slightlydifferent.co.nz/submitticket.php or to ***@***.***

For all other matters please raise a ticket only if urgent. Otherwise I will get back to you as soon as possible on my return.

Kind regards

Steve

**Comment by fritteli** [comment]
Any chance you could have a look at this pull request?

**Comment by kunalvarma05** [comment]
Thanks @fritteli!

**Comment by fritteli** [comment]
Great, thanks for merging!
Now all we need is a new release 😉

**Comment by kunalvarma05** [comment]
Tagged [v0.2.2](https://github.com/kunalvarma05/dropbox-php-sdk/releases/tag/v0.2.2) :)

**Comment by fritteli** [comment]
Awesome, thank you! ❤️

**Pull request merged**
